name: GitHub Actions - Elisa Image Build
env:
  YML_PATH: ../health-check/elisa/k8s.elisa.deployment.yml
  IMAGE_TAG: ghcr.io/${{ github.repository }}-elisa:${{ github.run_id }}
on:
  push:
    branches:
      - trunk
    paths:
      - "elisa/**"
      - ".github/workflows/elisa-image-build.yml"

jobs:
  Build-Elisa-DockerImage-Arm:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        env:
          DOCKER_BUILDKIT_SANDBOX_MODE: "disabled"
        with:
          context: "{{defaultContext}}"
          platforms: linux/arm64/v8
          push: true
          tags: ${{ env.IMAGE_TAG }}
  Deploy-In-Cluster:
    runs-on: self-hosted
    needs: Build-Elisa-DockerImage-Arm
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: un0ver-lnch/universe
          ref: refs/heads/trunk
          token: ${{ secrets.PAT }}
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: cd bigbang && bun install
      - name: Adjust deployment
        run: cd bigbang && NODE_TLS_REJECT_UNAUTHORIZED=0 bun run src/heath-check-agent-deploy.ts