name: GitHub Actions - Library Build
run-name: SO module building
env:
  REGISTRY: ghcr.io
on:
  push:
    branches:
      - trunk
    paths:
      - "bitsearch-health/**"
      - ".github/workflows/zig-bitsearch-health-check.yml"
jobs:
  Build-SO-Module:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.13.0 # released versions or master
      - name: Build zig so module
        run: cd bitsearch-health && zig build
      - name: Publish zig so module
        uses: actions/upload-artifact@v4
        with:
          name: zig-bitsearch-health
          path: bitsearch-health/zig-out/aarch64-linux-gnu/libbitsearch-health.so
      - name: Publish zig sidecar
        uses: actions/upload-artifact@v4
        with:
          name: zig-bitsearch-health-sidecar
          path: bitsearch-health/sidecar.json
  Deploy-Artifacts-Elisa:
    needs: Build-SO-Module
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: zig-bitsearch-health
          path: download/
      - name: Upload artifact to Elisia
        run: |
          curl http://elisa-health-service.health-check.svc.cluster.local:3000/upload --request PUT -F 'file=@download/libbitsearch-health.so' -F 'name=libbitsearch-health.so'
  Deploy-Artifacts-Sidecar-Elisa:
    needs: Build-SO-Module
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: zig-bitsearch-health-sidecar
          path: download/
      - name: Upload sidecar to Elisia
        run: |
          curl http://elisa-health-service.health-check.svc.cluster.local:3000/upload --request PUT -F 'file=@download/sidecar.json' -F 'name=libbitsearch-health.json'
  Restart-Pods:
    needs: [Deploy-Artifacts-Elisa, Deploy-Artifacts-Sidecar-Elisa]
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: un0ver-lnch/universe
          ref: refs/heads/trunk
          token: ${{ secrets.PAT }}
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: cd bigbang && bun install
      - name: Adjust deployment
        run: cd bigbang && NODE_TLS_REJECT_UNAUTHORIZED=0 FILER=health-check-agent NAMESPACE=health-check bun run src/rollout-deployment.ts
