name: GitHub Actions - Library Build
run-name: SO module building
env:
  REGISTRY: ghcr.io
on:
  push:
    branches:
      - trunk
    paths:
      - "bitseach-health/**"
      - ".github/workflows/zig-bitsearch-health-check.yml"
jobs:
  Build-SO-Module:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.13.0 # released versions or master
      - name: Build zig so module
        run: cd bitsearch-health && zig build
      - name: LS
        run: ls bitsearch-health
      - name: LS
        run: ls bitsearch-health/zig-out
      - name: LS
        run: ls bitsearch-health/zig-out/aarch64-linux-gnu
      - name: Publish zig so module
        uses: actions/upload-artifact@v4
        with:
          name: zig-bitsearch-health
          path: bitsearch-health/zig-out/aarch64-linux-gnu/libbitsearch-health.so