name: GitHub Actions - WASM Build
run-name: WASM module building
env:
  REGISTRY: ghcr.io
on:
  push:
    branches:
      - trunk
    paths:
      - "zig-hello-wasm/**"
      - ".github/workflows/zig-hello-world-wasm-build.yml"
jobs:
  Build-WASM-Module:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.13.0 # released versions or master
      - name: Build zig wasm module
        run: cd zig-hello-wasm && devenv shell zig build-exe main.zig -target wasm32-wasi
      - name: Publish zig wasm module
        uses: actions/upload-artifact@v4
        with:
          name: zig-hello-wasm
          path: zig-hello-wasm/main.wasm