name: GitHub Actions - WASM Build
run-name: WASM module building
env:
  REGISTRY: ghcr.io
on:
  push:
    branches:
      - trunk
    paths:
      - "zig-hello-wasm/**"
      - ".github/workflows/zig-hello-world-wasm-build.yml"
jobs:
  Build-WASM-Module:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up nixos
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Set up devenv
        run: nix-env -iA devenv -f https://github.com/NixOS/nixpkgs/tarball/nixpkgs-unstable
      - name: Build zig wasm module
        run: cd zig-hello-wasm && devenv shell zig build-exe main.zig -target wasm32-wasi
      - name: Publish zig wasm module
        uses: actions/upload-artifact@v4
        with:
          name: zig-hello-wasm
          path: zig-hello-wasm/main.wasm