name: GitHub Actions - Library Build
run-name: SO module building
env:
  REGISTRY: ghcr.io
on:
  push:
    branches:
      - trunk
    paths:
      - "bitsearch-health/**"
      - ".github/workflows/zig-bitsearch-health-check.yml"
jobs:
  Build-SO-Module:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.13.0 # released versions or master
      - name: Build zig so module
        run: cd bitsearch-health && zig build
      - name: Publish zig so module
        uses: actions/upload-artifact@v4
        with:
          name: zig-bitsearch-health
          path: bitsearch-health/zig-out/aarch64-linux-gnu/libbitsearch-health.so
      - name: Publish zig sidecar
        uses: actions/upload-artifact@v4
        with:
          name: zig-bitsearch-health-sidecar
          path: bitsearch-health/sidecar.json
  Deploy-Artifacts-Elisa:
    needs: Build-SO-Module
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: zig-bitsearch-health
          path: download/
      - name: Upload artifact to Elisia
        run: |
          curl http://elisa-health-service.health-check.svc.cluster.local:3000/upload --request PUT -F 'file=@download/libbitsearch-health.so' -F 'name=libbitsearch-health.so'
  Deploy-Artifacts-Sidecar-Elisa:
    needs: Build-SO-Module
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: zig-bitsearch-health-sidecar
      - name: Upload sidecar to Elisia
        run: |
          curl http://elisa-health-service.health-check.svc.cluster.local:3000/upload --request PUT -F 'file=@download/sidecar.json' -F 'name=libbitsearch-health.json'
  Restart-Pods:
    if: false
    needs: Deploy-Artifacts-Elisa
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: azure/setup-kubectl@v4
        id: install
      - name: Config kubectl
        run: |
          echo "$KUBECONFIG_CI" > kubeconfig
          export KUBECONFIG=$(pwd)/kubeconfig
          kubectl get pods
        env:
          KUBECONFIG_CI: ${{ secrets.KUBECONFIG_CI }}
      - name: Restart pods
        run: |
          kubectl rollout restart deployment health-check-agent -n health-check
